---
language: node_js
node_js:
  - "7"

sudo: false

services:
  - elasticsearch

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - libssl-dev
      - gcc-4.9-multilib
      - g++-4.9-multilib
      - lcov
env:
 - CC=clang
 - CXX=clang++
 - npm_config_clang=1
 - GYP_DEFINES="use_obsolete_asm=true"

compiler: clang

cache:
  directories:
    - $HOME/.npm
    - $HOME/.cache # includes bowers cache
    - $HOME/.yarn-cache

before_install:
  - npm config set spin false
  - npm install -g bower phantomjs-prebuilt yarn
  - bower --version
  - phantomjs --version

install:
  - yarn install

before_script:
 - ln -s ../packages node_modules/@cardstack

script:
  - ELASTICSEARCH=http://localhost:9200 npm test
