---
language: node_js
node_js:
  - "7"

sudo: false

addons:
  firefox: latest
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - libssl-dev
      - gcc-4.9-multilib
      - g++-4.9-multilib
      - lcov
      - oracle-java8-installer

compiler: clang

env:
  global:
    - CC=clang
    - CXX=clang++
    - npm_config_clang=1
    - GYP_DEFINES="use_obsolete_asm=true"
    - ES_VERSION=5.1.2
    - ELASTICSEARCH=http://127.0.0.1:9200 
    - JAVA_HOME=/usr/lib/jvm/java-8-oracle

cache:
  yarn: true
  directories:
    - packages/authentication/node_modules
    - packages/bundler/node_modules
    - packages/core-types/node_modules
    - packages/di/node_modules
    - packages/drupal/node_modules
    - packages/elasticsearch/node_modules
    - packages/email-auth/node_modules
    - packages/ephemeral/node_modules
    - packages/eslint-config/node_modules
    - packages/git/node_modules
    - packages/github-auth/node_modules
    - packages/handlebars/node_modules
    - packages/hub/node_modules
    - packages/image/node_modules
    - packages/jsonapi/node_modules
    - packages/mobiledoc/node_modules
    - packages/models/node_modules
    - packages/plugin-utils/node_modules
    - packages/routing/node_modules
    - packages/search/node_modules
    - packages/test-support/node_modules
    - packages/tools/node_modules
    - packages/codegen/node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add phantomjs-prebuilt lerna
  - phantomjs --version
  - java -version

install:
  - yarn install
  - travis_wait lerna bootstrap
  - wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz
  - tar -xzf elasticsearch-${ES_VERSION}.tar.gz
  - ./elasticsearch-${ES_VERSION}/bin/elasticsearch 2>&1 > /tmp/es.log &

before_script:
 - export DISPLAY=:99; sh -e /etc/init.d/xvfb start; sleep 3
 - wget -q --waitretry=1 --retry-connrefused -T 1 -O - http://127.0.0.1:9200 || cat /tmp/es.log

script:
  - yarn test
